<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){

	$('#searchButton').click(function(evt) {

		var data = $('#data').val();
		
		$.ajax({
	        url: 'http://test.api.local/api/woood-order/create-test',
	        type: 'POST',
	        data: { data: data },
	        dataType: 'json',
	        success: function(data) {
	        	$('#result').html(data);
	        },
	        error: function(jqXHR, textStatus, errorThrown) {
				var status = textStatus;
	        }
	    });
		
	});
	
});
</script>

<form action="#" method="post">
	<label for="data">Maak order aan</label>
	<textarea id="data" name="data">{
{
"header":
{
"api-key": "v3U52X3vfA8TH9BEAfM6kU76roDPZbhKZEp3URJf",
"username": "bol",
"password": "QKxB=YjwMM2t"
},
"body":
{
"order":
{
"REFERENTIE": "TEST_ORDER_F6u16dKf",
"OMSCHRIJVING": "TEST_ORDER_F6u16dKf",
"DEBITEURNR": "160405",
"SELECTIECODE": "CA",
"ORDERTOELICHTING": "EffectConnect",
"DS_NAAM": "Jules Dohmen (TESTORDER)",
"DS_AANSPREEKTITEL": "M",
"DS_ADRES1": "Tolhuisweg 5A",
"DS_POSTCODE": "6071RG",
"DS_PLAATS": "Swalmen",
"DS_LAND": "NL",
"DS_TELEFOON": "0859021855",
"DS_EMAIL": "Info@koekenpeer.nl",
"item": [
{
"ITEMCODE": "341206-Z",
"AANTAL": 1
}
]
}
}
}
	
	  </textarea><br><br>
	<button type="button" id="searchButton">Uitvoeren</button>
</form>

Antwoord:
<div id="result"></div>